-- COPYRIGHT San Francisco State University SCS648 Team 4 - SP22
-- Script name: DB_BusyGator.sql
-- Author:      CSC 648 Team 04
-- Purpose:     this is the database model used to construct the tables in the database
--
-- MySQL Script generated by MySQL Workbench
-- Sat Apr  2 17:14:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database: `DB_BusyGator`
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `DB_BusyGator` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `DB_BusyGator`;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT(9) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `administrator` TINYINT NOT NULL DEFAULT 0,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category`;
CREATE TABLE IF NOT EXISTS `category` (
  `category_id` INT(9) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;



--
-- Dumping data for table `category`
--

INSERT INTO `category` (`category_id`, `name`, `description`) VALUES
(1, 'Electronics', 'euanfaofa'),
(2, 'Pets', 'awdwada'),
(3, 'Home', 'adwwad'),
(4, 'Recreational', 'igoker'),
(5, 'Books', 'uindwajkm');



-- -----------------------------------------------------
-- Table `location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `location`;
CREATE TABLE IF NOT EXISTS `location` (
  `location_id` INT(9) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;

--
-- Dumping data for table `location`
--



INSERT INTO `location` (`location_id`, `name`) VALUES
(1, 'Annex I & Annex II'),
(2, 'University Park North'),
(3, 'Hensill Hall'),
(4, 'Gymnasium'),
(5, 'J. Paul Leonard Library'),
(6, 'Manzanita Square'),
(7, 'University Park South'),
(8, 'Masshouf Wellness Center'),
(9, 'Parking Garage'),
(10, 'Cox Stadium');

-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product`;
CREATE TABLE IF NOT EXISTS `product` (
  `product_id` INT(9) NOT NULL,
  `seller_id` INT(9) NOT NULL,
  `category` INT(9) NOT NULL,
  `location` INT(9) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(120) NULL,
  `image` VARCHAR(4096) NULL,
  `image_thumbnail` VARCHAR(4096) NULL,
  `price` DOUBLE NOT NULL,
  `approved` TINYINT NOT NULL DEFAULT 0,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `product_id_UNIQUE` (`product_id` ASC),
  INDEX `category_id_UNIQUE` (`category` ASC),
  INDEX `location_UNIQUE` (`location` ASC),
  INDEX `seller_id_UNIQUE` (`seller_id` ASC),
  CONSTRAINT `PRODUCT_CATEGORY_FK`
    FOREIGN KEY (`category`)
    REFERENCES `category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PRODUCT_LOCATION_FK`
    FOREIGN KEY (`location`)
    REFERENCES `location` (`location_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PRODUCT_USER1_FK`
    FOREIGN KEY (`seller_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message`;
CREATE TABLE IF NOT EXISTS `message` (
  `message_id` INT(9) NOT NULL,
  `creator_id` INT(9) NOT NULL,
  `receiver_id` INT(9) NOT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `message_body` VARCHAR(500) NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `MESSAGE_USER_FK_idx` (`creator_id` ASC),
  INDEX `MESSAGE_USER2_FK_idx` (`receiver_id` ASC),
  INDEX `creator_id_UNIQUE` (`creator_id` ASC),
  INDEX `receiver_id_UNIQUE` (`receiver_id` ASC),
  CONSTRAINT `MESSAGE_USER1_FK`
    FOREIGN KEY (`creator_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MESSAGE_USER2_FK`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
